apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: leaky-express-example1:1.0
        # lifecycle:
        #   preStop:
        #     exec:
        #       command:
        #         - sh
        #         - -c
        #         - "curl -x GET http://localhost:1337/heapdump"
        #         - "sleep 2m"
        volumeMounts:
        - name: dumps
          mountPath: /opt/dumps
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      volumes:
      - name: dumps
        hostPath:
          path: /opt/dumps
      # extend termination time for container
      # terminationGracePeriodSeconds: 90
---
apiVersion: v1
kind: Service
metadata:
  name: express
spec:
  selector:
    app: express
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express
  labels:
    name: express
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: express
            port: 
              number: 3000
